### ISSUE TITLE
Setup hooks for Travis + Packagist

### ISSUE THREAD

**Issue by barryvdh** [thephpleague/omnipay-braintree#1]
@kayladnls can you add this package to Packagist and enable the Travis builds?

**Comment by barryvdh** [comment]
*ping* 
Or should I ask @philsturgeon or some other admin?
I can't add Packagist because I'm not an admin of the repo.

**Comment by kayladnls** [comment]
Done.

**Comment by barryvdh** [comment]
Thanks!
