### ISSUE TITLE
Has the dependent braintree/braintree_php library been dropped from V3.1.0 to V2.40.0?

### ISSUE THREAD

**Issue by rquadling** [thephpleague/omnipay-braintree#10]
Hi.

Just seeing this as a change in my composer.lock file.

Considering this a significant step backwards on a dependant library's version number, I'm just wanting to check/confirm.

Thanks.

**Comment by 1ed** [comment]
Ohhh, that was my mistake... sorry for that. Fixed in #11

**Comment by rquadling** [comment]
Ha! Peer review working? :heavy_check_mark:

**Comment by barryvdh** [comment]
It allows 2.x for now, but might bump it back to v3 when it's actually needed.
