### ISSUE TITLE
A basic guide to using Braintree (with this lib)

### ISSUE THREAD

**Issue by collizo4sky** [thephpleague/omnipay-braintree#12]
Hi, i wanna use this package on a store am building. Problem is, i don't understand how Braintree works.

Can some one help explain how to use braintree with this package? Am confused about generating payment method nonce, token etc.

Any help i can get would be appreciated.

Cc @1ed @iampersistent .

**Comment by iampersistent** [comment]
I could make some time this weekend to help you out. Message me the best
email address for you

**Comment by collizo4sky** [comment]
Sure. my email is me@w3guy.com skype is tech4sky

Might want to send me your skype ID.

If you are less busy by tomorrow (weekend), let's do this.

**Comment by kayladnls** [comment]
I can also help, if you you're not able to get all the information you need.

**Comment by collizo4sky** [comment]
I would need all the help i can get. @kayladnls Would you consider writing a manual on it or over help over skype?

**Comment by barryvdh** [comment]
Did you read http://omnipay.thephpleague.com/ ?

The only thing different about using Braintree, is that you need to use the Client SDK from braintree to generate the nonce, see https://developers.braintreepayments.com/start/hello-client/javascript/v2

```
// Setup payment gateway
$gateway = Omnipay::create('Braintree');
$gateway->setMerchantId('abc123');
$gateway->setPublicKey('abc123');
$gateway->setPrivateKey('abc123');

$clientToken = $gateway->clientToken()->send()->getToken();
```
Use the client token to render the script. You then post the form, including the generated nonce to your php script, and use the nonce to make the transaction.

```
$response = $gateway->purchase([
            'amount' => '10.00',
            'token' => $_POST['payment_method_nonce']
        ])->send();
```

**Comment by collizo4sky** [comment]
@barryvdh i know how Omnipay works. I built the WePay driver.


Thanks everyone, i finally got it to work.

**Comment by barryvdh** [comment]
Okay good, Please let us know what we can add to the readme to make it clear for others :)

**Comment by collizo4sky** [comment]
@barryvdh Just submitted a PR to that regard. See #13
