### ISSUE TITLE
Sending Email / Customer Attributes

### ISSUE THREAD

**Issue by MR-ScottH** [thephpleague/omnipay-braintree#20]
Hi,

I have a working integration of braintree however i am unable to pass through customer details (examples at https://developers.braintreepayments.com/reference/request/transaction/sale/php#customer )

I cant seem to find any guides on how to send more details through the braintree module. i am currently trying to add it as an additional option but it is not being picked up. 

Any ideas?

**Comment by alok932** [comment]
This is what i am doing and its working (this also adds payment method to customer)

`$cardresponse = $gateway->createCustomer(array(
                                                   'customerData' => [
                                                      'firstName'=>'Drew',
                                                      'lastName'=>'smith',
                                                      'email' =>'drew@example.com',
                                                      'paymentMethodNonce' => $token
                                                    ]
                                                  )
                                              )->send();`
