### ISSUE TITLE
Use omnipay-braintree to pay with paypal

### ISSUE THREAD

**Issue by sprik** [thephpleague/omnipay-braintree#29]
Hi,

which is the flow to make a payment with omnipay-braintree plugin?
Braintree allows to pay with paypal, but I can't find something like that with the omnipay-braintree gateway.

Best Regards

**Comment by delatbabel** [comment]
Hi,

I'm not sure to be exact.

Just a reminder that this isn't a support forum. This is a bug tracker to identify and fix known bugs in omnipay. The correct support forum for omnipay is in fact StackOverflow and so I suggest that you submit your question there. Tag it with both `omnipay` and `braintree` tags and that way you're more likely to get answers from omnipay and braintree users who will know the answer to your question.
