### ISSUE TITLE
Braintree find customer not working

### ISSUE THREAD

**Issue by akberkhan1990** [thephpleague/omnipay-braintree#34]
Hi,
i am working on laravel api, integrated omnipay/braintree, i have successfully created my customer, what i need to get customer data through this,
 $mycustomer = $omnipay_gateway->findCustomer(5)->send();
but it giving me bad response like,

<pre>Omnipay\Braintree\Message\CustomerResponse Object
(
    [request:protected] => Omnipay\Braintree\Message\FindCustomerRequest Object
        (
            [braintree:protected] => Braintree\Gateway Object
                (
                    [config] => Braintree\Configuration Object

its a huge chunck of data which i am not pasting here, how i get my customer details through this type of data, and it shows in this format, why not in proper json or some other format?

**Comment by delatbabel** [comment]
JSON is a data format.  It is represented in memory by PHP objects.  You should examine the config object and extract the data that you need from it.
