### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by shackrock** [thephpleague/omnipay-braintree#35]
I noticed that the braintree gateway was not listed on the website in either official or 3rd party repos - is this still being maintained / updated?

http://omnipay.thephpleague.com/gateways/official/
http://omnipay.thephpleague.com/gateways/third-party/

Thanks

**Comment by delatbabel** [comment]
Yes, but those sites are not up to date.  Please check here for the latest gateway list: https://github.com/thephpleague/omnipay
