### ISSUE TITLE
Dependencies collisions omnipay/braintree + laravel/framework 5.6

### ISSUE THREAD

**Issue by puggan** [thephpleague/omnipay-braintree#38]
Reproduce:
Add both Laravel and omnipay to a composer-require:

```
    "require": {
        "laravel/framework": "5.6.*",
        "omnipay/braintree": "*"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
```

run `composer install`

Full log in attatchment, the collision:
omnipay/braintree requires omnipay/common 2
omnipay/common 2 requires symfony/http-foundation 3
laravel/framework 5.6 requires symfony/http-foundation 4
omnipay/common 3 requires symfony/http-foundation 4

**Comment by barryvdh** [comment]
This will be fixed with Omnipay v3. You can create a PR for that if you want.
