### ISSUE TITLE
Braintree package is not installing using composer

### ISSUE THREAD

**Issue by dexbytes** [thephpleague/omnipay-braintree#51]
We are trying to install the braintree package in laravel 5.7 but it is throwing error.

PHP version at server is 7.2.24

- nesbot/carbon 1.39.0 requires kylekatarnls/update-helper ^1.1 -> satisfiable by kylekatarnls/update-helper[1.1.0, 1.1.1, 1.2.0].

Can you please check and let us know the reason behind.

**Comment by barryvdh** [comment]
I don't think this is related to this package directly?

**Comment by dexbytes** [comment]
It is sorted when composer version udpated.
