### ISSUE TITLE
Undefined variable $items

### ISSUE THREAD

**Issue by mambose** [thephpleague/omnipay-braintree#67]
Looks like a bug in the code here. I am having trouble submitting line items to Braintree and getting an `Undefined variable $items` error.

https://github.com/thephpleague/omnipay-braintree/blob/2d49d595ce684b7c2ea3a26bd1dd45f13c77f030/src/Message/AbstractRequest.php#L442

Changing the `if` statement above it to

`if (!$items = $this->getItems()) {`

seems to fix the issue.

**Comment by timeverts** [comment]
@barryvdh, @barrycarrjr, would really love for this bug to be fixed too.

Any idea on an ETA?

**Comment by barryvdh** [comment]
Can you create an PR?

**Comment by timeverts** [comment]
Thanks @barryvdh 
See  https://github.com/thephpleague/omnipay-braintree/pull/68

If possible, please integrate and push out a release to packagist too.
