### ISSUE TITLE
Do you guys know how to incorporate this to store 2 on expressionengine?

### ISSUE THREAD

**Issue by pedrosuazo** [thephpleague/omnipay-braintree#7]
Hi, am using expresso store 2 on expressionengine, l try to install this files on expressionengine but l keep getting errors, do you know how to incorporate this to expressionengine?
![error payment](https://cloud.githubusercontent.com/assets/7330163/10651613/36470d0a-7816-11e5-9921-7eef2542447f.png)

**Comment by barryvdh** [comment]
No sorry.

**Comment by kayladnls** [comment]
I'm not familiar with expression engine, sorry. That would probably be under the purview of Expresso Store 2 team.
